version: '3'
services:
  app:
    build: './php'
    volumes:
      - '../src:/var/www/html'

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8088:80'
    volumes:
      - '../src:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'QWE123rty'